# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'plasma/kwayland': '@latest-kf6'
